/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function astEdit(options: AstReplaceOptions): Promise<AstReplaceResult>

export interface AstFindMatch {
  path: string
  text: string
  byteStart: number
  byteEnd: number
  startLine: number
  startColumn: number
  endLine: number
  endColumn: number
  metaVariables?: Record<string, string>
}

export interface AstFindOptions {
  patterns?: Array<string>
  lang?: string
  path?: string
  glob?: string
  selector?: string
  strictness?: AstMatchStrictness
  limit?: number
  offset?: number
  includeMeta?: boolean
  context?: number
  signal?: unknown
  timeoutMs?: number
}

export interface AstFindResult {
  matches: Array<AstFindMatch>
  totalMatches: number
  filesWithMatches: number
  filesSearched: number
  limitReached: boolean
  parseErrors?: Array<string>
}

export declare function astGrep(options: AstFindOptions): Promise<AstFindResult>

export declare function astMatch(options: AstMatchOptions): Promise<AstMatchResult>

export interface AstMatchOptions {
  source: string
  lang: string
  patterns: Array<string>
  selector?: string
  strictness?: AstMatchStrictness
  limit?: number
  offset?: number
  includeMeta?: boolean
  signal?: unknown
  timeoutMs?: number
}

export interface AstMatchResult {
  matches: Array<AstFindMatch>
  totalMatches: number
  limitReached: boolean
  parseErrors?: Array<string>
}

/** ast-grep pattern strictness (controls how patterns match syntax). */
export declare const enum AstMatchStrictness {
  Cst = 'cst',
  Smart = 'smart',
  Ast = 'ast',
  Relaxed = 'relaxed',
  Signature = 'signature',
  Template = 'template'
}

export interface AstReplaceChange {
  path: string
  before: string
  after: string
  byteStart: number
  byteEnd: number
  deletedLength: number
  startLine: number
  startColumn: number
  endLine: number
  endColumn: number
}

export interface AstReplaceFileChange {
  path: string
  count: number
}

export interface AstReplaceOptions {
  rewrites?: Record<string, string>
  lang?: string
  path?: string
  glob?: string
  selector?: string
  strictness?: AstMatchStrictness
  dryRun?: boolean
  maxReplacements?: number
  maxFiles?: number
  failOnParseError?: boolean
  signal?: unknown
  timeoutMs?: number
}

export interface AstReplaceResult {
  changes: Array<AstReplaceChange>
  fileChanges: Array<AstReplaceFileChange>
  totalReplacements: number
  filesTouched: number
  filesSearched: number
  applied: boolean
  limitReached: boolean
  parseErrors?: Array<string>
}
